emacs-lsp/lsp-metals

lsp-metals.el

It's required by lsp-metals-treeview but not specified in the list of dependencies.

Require lsp-treemacs.

---

lsp-metals-treeview.el

json-serialize can't serialize list, only vector.
Fixes https://github.com/emacs-lsp/lsp-metals/issues/24

Fix treeview in emacs 27.

---

lsp-metals.el

Added  metals.copy-worksheet-output introduced (I think) in [this metals PR](https://github.com/scalameta/metals/pull/2290).
Implementation is based on [PR from coc-emacs](https://github.com/scalameta/coc-metals/pull/360).
Happy to fix code if there are any issues 😄

feature: add metals.copy-worksheet-output

---

lsp-metals.el

Hi, 
I came across two `lsp-metals-scalafmt-config-path` variables. Is it intentional?
I think it is duplicated. Also, I am not sure if I am deleting the correct one.
Best,

Remove duplicated lsp-metals-scalafmt-config-path

---

lsp-metals-treeview.el

build-28.0.50/lsp-metals/lsp-metals-treeview.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode'

Fix deprecation notice on define-minor-mode

---

lsp-metals.el

This is to support project layouts that don't have an umbrella module with name `root` which encompasses all submodules. More details can be found in the corresponding issue (https://github.com/emacs-lsp/lsp-metals/issues/57).
This change introduces a new setting `projectId` which can be specified as part of the DAP configuration template. Here is an example of a template which uses a new setting:
```
(dap-register-debug-template
"Scala Attach Core"
(list :type "scala"
:request "attach"
:name "Scala Attach Core"
:projectId "core"
:hostName "localhost"
:port 5005))
```

Resolve #57. Add project ID setting support to DAP debug templates to allow values other than 'root'

---

lsp-metals.el

This was changed by mistake by me, when doing some refactorings.
Found in lsp--text-document-position-params
I haven't tested it and if anyone could confirm it works I would be super thankful :pray:

Fix recently changed super-method-hierarchy command

---

lsp-metals.el

All methods are named `lsp-metals-view-` followed by the desired format.
* lsp-metals-view-javap
* lsp-metals-view-javap-verbose
* lsp-metals-view-semanticdb-compact
* lsp-metals-view-semanticdb-detailed
* lsp-metals-view-tasty-decoded
No buffer mode is set for the resulting buffer. Is there an appropriate mode? 
The names are ugly.

Add functions for metals.file-decode

---

lsp-metals-treeview.el

They are already quoted so they mean `''Metals-light` and `''Metals-dark`. It is wrong.
Development Emacs warns this as byte-compile warnings as below.
```
lsp-metals-treeview.el:82:12: Warning: defcustom for
‘lsp-metals-treeview-theme’ has syntactically odd type ‘'(choice (const
:tag Light 'Metals-light) (const :tag Dark 'Metals-dark))’
```

Remove needless quote

---

lsp-metals.el

Hi, this PR adds all user configuration options from https://scalameta.org/metals/docs/editors/user-configuration/.
Additionally, AFAICS `metals.pants-targets` is no longer an option, so I've marked it as deprecated, and I've tweaked the docstring of `metals.scalafmt-config-path` to make it clear that the value for this option should be an absolute path (https://github.com/scalameta/metals/pull/2165).
I've set `:package-version` for the new options to `1.3`, I can change it to something like `unreleased` if you want.

Add More Configuration Options

---

lsp-metals-treeview.el

This is a quick fix for #84, which at least gets us rid of the "Symbol's definition is void" error. We should eventually migrate to the API provided by treemacs-treelib.

Require treemacs-extensions explicitly

---

.github/workflows/test.yml
Eask
Makefile

tests(Makefile): Update eask's commands

---

lsp-metals.el

Hi, this PR activates `java-mode` in javap buffers generated by `lsp-metals--decode`:
and makes `lsp-metals-decode-file` a command which when not passed a format-id, will prompt the user for one from a preset list. I've also `defconst`ed all of the format ids so that they're not duplicated.
I hope this is helpful, thanks :slightly_smiling_face:

Fontify javap buffers in lsp-metals--decode

---

README.md
lsp-metals.el

Hi, this PR adds a new command `lsp-metals-run-scalafix` which runs the `scalafix-run` command (documentation: https://scalameta.org/metals/docs/integrations/new-editor/#run-all-scalafix-rules).
~I've also added a utility function for adding this command to `before-save-hook`, and added this to the example setup~.  I hope this is helpful, thanks :slightly_smiling_face:

Add a Command to Run 'scalafix-run'

---

.github/workflows/test.yml
CHANGELOG.md
Eask
lsp-metals.el

See https://github.com/emacs-lsp/lsp-mode/pull/4126.

fix: Drop Emacs 26.x

---

lsp-metals.el

Hi!  I sometimes find it convenient to jump to the current server log, and I thought it might be useful if there was a command for it.
Thanks!

Add convenience command lsp-metals-open-server-log

---

lsp-metals.el

scala-mode 1.1 does not exist; 0.23 is the current version. 
https://github.com/hvesalai/emacs-scala-mode/blob/master/scala-mode.el#L7
This breaks installing lsp-metals in my setup (use-package with elpaca).
1.1 was set as the dependency in https://github.com/emacs-lsp/lsp-metals/pull/48. I didn't chase why this was set any further than that.

update required scala-mode version: 1.1 -> 0.23

---

Eask

Fixes error:
```
Unmatched summary 'Scala Client settings '; it should be 'Scala Client settings'
```

Eask config typo

---

lsp-metals.el

Remove metals/windowStateDidChange notification.

---

.github/workflows/test.yml

`aarch64-darwin` build is failing for 27.2:
https://github.com/emacs-lsp/lsp-metals/actions/runs/12587001261/job/35081969020#step:3:335
Dependency https://github.com/purcell/nix-emacs-ci does not support it:
> Official release versions from 23.4 are supported on Linux; from 24.3 on Intel MacOS; and from 28.1 on ARM (Apple Silicon) MacOS

remove unsupported 27.2 CI coverage; add `aarch64-linux` coverage

---

lsp-metals-treeview.el

Without this check they can be send to add-on servers which is wrong.

Make sure treeview requests are sent only to metals.
